#include "std.h"

symbol_definition_t symbols[] = {{"assign", std_assign},
                                 {"function", std_function},
                                 {"include", std_include},
                                 {"return", std_return},
                                 {"random", std_random},
                                 {"exit", std_exit},
                                 {"while", std_while},
                                 {"dotimes", std_dotimes},
                                 {"console.print", std_console_print},
                                 {"console.println", std_console_println},
                                 {"console.readln", std_console_readln},
                                 {"add", std_math_add},
                                 {"sub", std_math_sub},
                                 {"mul", std_math_mul},
                                 {"div", std_math_div},
                                 {"mod", std_math_mod},
                                 {"pow", std_math_pow},
                                 {"if", std_if},
                                 {"elif", std_elif},
                                 {"equal", std_equal},
                                 {"not", std_not},
                                 {"greater", std_greater},
                                 {"less", std_less},
                                 {"greater_equal", std_greater_equal},
                                 {"less_equal", std_less_equal},
                                 {"string.split", std_string_split},
                                 {"string.replace", std_string_replace},
                                 {"string.append", std_string_append},
                                 {"file.read", std_file_read},
                                 {"file.write", std_file_write},
                                 {"string?", std_types_string_check},
                                 {"number?", std_types_number_check},
                                 {"list?", std_types_list_check},
                                 {"string", std_types_string},
                                 {"number", std_types_number},
                                 {"newstring", std_types_string},
                                 {"newnumber", std_types_number},
                                 {"list", std_list},
                                 {"newlist", std_list},
                                 {"list.get", std_list_get},
                                 {"list.set", std_list_set},
                                 {"list.append", std_list_append},
                                 {"list.do", std_list_do},
                                 {"list.range", std_list_range},
                                 {"list.copy", std_list_copy},
                                 {"length", std_length},
                                 NULL};

symbol_definition_t *
module_init (void)
{
    return symbols;
}
